// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzxqomrrhuqoyqrlbxpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6eHFvbXJyaHVxb3lxcmxieHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjA2NTgsImV4cCI6MjA2NzQ5NjY1OH0.sHhqcdk88Pj-sdhSx11a488CrgX8fjYFIHxhvUv10mA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});